name: deploy-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      distribution_id: E3FWQLYH2W4XLU
    secrets: inherit
